/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ConversorAJuliano */

#ifndef _Included_ConversorAJuliano
#define _Included_ConversorAJuliano
#ifdef __cplusplus
extern "C" {
#endif
#undef ConversorAJuliano_FOCUS_TRAVERSABLE_UNKNOWN
#define ConversorAJuliano_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef ConversorAJuliano_FOCUS_TRAVERSABLE_DEFAULT
#define ConversorAJuliano_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef ConversorAJuliano_FOCUS_TRAVERSABLE_SET
#define ConversorAJuliano_FOCUS_TRAVERSABLE_SET 2L
#undef ConversorAJuliano_TOP_ALIGNMENT
#define ConversorAJuliano_TOP_ALIGNMENT 0.0f
#undef ConversorAJuliano_CENTER_ALIGNMENT
#define ConversorAJuliano_CENTER_ALIGNMENT 0.5f
#undef ConversorAJuliano_BOTTOM_ALIGNMENT
#define ConversorAJuliano_BOTTOM_ALIGNMENT 1.0f
#undef ConversorAJuliano_LEFT_ALIGNMENT
#define ConversorAJuliano_LEFT_ALIGNMENT 0.0f
#undef ConversorAJuliano_RIGHT_ALIGNMENT
#define ConversorAJuliano_RIGHT_ALIGNMENT 1.0f
#undef ConversorAJuliano_serialVersionUID
#define ConversorAJuliano_serialVersionUID -7644114512714619750i64
#undef ConversorAJuliano_serialVersionUID
#define ConversorAJuliano_serialVersionUID 4613797578919906343i64
#undef ConversorAJuliano_INCLUDE_SELF
#define ConversorAJuliano_INCLUDE_SELF 1L
#undef ConversorAJuliano_SEARCH_HEAVYWEIGHTS
#define ConversorAJuliano_SEARCH_HEAVYWEIGHTS 1L
#undef ConversorAJuliano_OPENED
#define ConversorAJuliano_OPENED 1L
#undef ConversorAJuliano_serialVersionUID
#define ConversorAJuliano_serialVersionUID 4497834738069338734i64
#undef ConversorAJuliano_DEFAULT_CURSOR
#define ConversorAJuliano_DEFAULT_CURSOR 0L
#undef ConversorAJuliano_CROSSHAIR_CURSOR
#define ConversorAJuliano_CROSSHAIR_CURSOR 1L
#undef ConversorAJuliano_TEXT_CURSOR
#define ConversorAJuliano_TEXT_CURSOR 2L
#undef ConversorAJuliano_WAIT_CURSOR
#define ConversorAJuliano_WAIT_CURSOR 3L
#undef ConversorAJuliano_SW_RESIZE_CURSOR
#define ConversorAJuliano_SW_RESIZE_CURSOR 4L
#undef ConversorAJuliano_SE_RESIZE_CURSOR
#define ConversorAJuliano_SE_RESIZE_CURSOR 5L
#undef ConversorAJuliano_NW_RESIZE_CURSOR
#define ConversorAJuliano_NW_RESIZE_CURSOR 6L
#undef ConversorAJuliano_NE_RESIZE_CURSOR
#define ConversorAJuliano_NE_RESIZE_CURSOR 7L
#undef ConversorAJuliano_N_RESIZE_CURSOR
#define ConversorAJuliano_N_RESIZE_CURSOR 8L
#undef ConversorAJuliano_S_RESIZE_CURSOR
#define ConversorAJuliano_S_RESIZE_CURSOR 9L
#undef ConversorAJuliano_W_RESIZE_CURSOR
#define ConversorAJuliano_W_RESIZE_CURSOR 10L
#undef ConversorAJuliano_E_RESIZE_CURSOR
#define ConversorAJuliano_E_RESIZE_CURSOR 11L
#undef ConversorAJuliano_HAND_CURSOR
#define ConversorAJuliano_HAND_CURSOR 12L
#undef ConversorAJuliano_MOVE_CURSOR
#define ConversorAJuliano_MOVE_CURSOR 13L
#undef ConversorAJuliano_NORMAL
#define ConversorAJuliano_NORMAL 0L
#undef ConversorAJuliano_ICONIFIED
#define ConversorAJuliano_ICONIFIED 1L
#undef ConversorAJuliano_MAXIMIZED_HORIZ
#define ConversorAJuliano_MAXIMIZED_HORIZ 2L
#undef ConversorAJuliano_MAXIMIZED_VERT
#define ConversorAJuliano_MAXIMIZED_VERT 4L
#undef ConversorAJuliano_MAXIMIZED_BOTH
#define ConversorAJuliano_MAXIMIZED_BOTH 6L
#undef ConversorAJuliano_serialVersionUID
#define ConversorAJuliano_serialVersionUID 2673458971256075116i64
#undef ConversorAJuliano_EXIT_ON_CLOSE
#define ConversorAJuliano_EXIT_ON_CLOSE 3L
/*
 * Class:     ConversorAJuliano
 * Method:    calcularJuliano
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_ConversorAJuliano_calcularJuliano
  (JNIEnv *, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
