/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MenuPrincipal */

#ifndef _Included_MenuPrincipal
#define _Included_MenuPrincipal
#ifdef __cplusplus
extern "C" {
#endif
#undef MenuPrincipal_FOCUS_TRAVERSABLE_UNKNOWN
#define MenuPrincipal_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef MenuPrincipal_FOCUS_TRAVERSABLE_DEFAULT
#define MenuPrincipal_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef MenuPrincipal_FOCUS_TRAVERSABLE_SET
#define MenuPrincipal_FOCUS_TRAVERSABLE_SET 2L
#undef MenuPrincipal_TOP_ALIGNMENT
#define MenuPrincipal_TOP_ALIGNMENT 0.0f
#undef MenuPrincipal_CENTER_ALIGNMENT
#define MenuPrincipal_CENTER_ALIGNMENT 0.5f
#undef MenuPrincipal_BOTTOM_ALIGNMENT
#define MenuPrincipal_BOTTOM_ALIGNMENT 1.0f
#undef MenuPrincipal_LEFT_ALIGNMENT
#define MenuPrincipal_LEFT_ALIGNMENT 0.0f
#undef MenuPrincipal_RIGHT_ALIGNMENT
#define MenuPrincipal_RIGHT_ALIGNMENT 1.0f
#undef MenuPrincipal_serialVersionUID
#define MenuPrincipal_serialVersionUID -7644114512714619750i64
#undef MenuPrincipal_serialVersionUID
#define MenuPrincipal_serialVersionUID 4613797578919906343i64
#undef MenuPrincipal_INCLUDE_SELF
#define MenuPrincipal_INCLUDE_SELF 1L
#undef MenuPrincipal_SEARCH_HEAVYWEIGHTS
#define MenuPrincipal_SEARCH_HEAVYWEIGHTS 1L
#undef MenuPrincipal_OPENED
#define MenuPrincipal_OPENED 1L
#undef MenuPrincipal_serialVersionUID
#define MenuPrincipal_serialVersionUID 4497834738069338734i64
#undef MenuPrincipal_DEFAULT_CURSOR
#define MenuPrincipal_DEFAULT_CURSOR 0L
#undef MenuPrincipal_CROSSHAIR_CURSOR
#define MenuPrincipal_CROSSHAIR_CURSOR 1L
#undef MenuPrincipal_TEXT_CURSOR
#define MenuPrincipal_TEXT_CURSOR 2L
#undef MenuPrincipal_WAIT_CURSOR
#define MenuPrincipal_WAIT_CURSOR 3L
#undef MenuPrincipal_SW_RESIZE_CURSOR
#define MenuPrincipal_SW_RESIZE_CURSOR 4L
#undef MenuPrincipal_SE_RESIZE_CURSOR
#define MenuPrincipal_SE_RESIZE_CURSOR 5L
#undef MenuPrincipal_NW_RESIZE_CURSOR
#define MenuPrincipal_NW_RESIZE_CURSOR 6L
#undef MenuPrincipal_NE_RESIZE_CURSOR
#define MenuPrincipal_NE_RESIZE_CURSOR 7L
#undef MenuPrincipal_N_RESIZE_CURSOR
#define MenuPrincipal_N_RESIZE_CURSOR 8L
#undef MenuPrincipal_S_RESIZE_CURSOR
#define MenuPrincipal_S_RESIZE_CURSOR 9L
#undef MenuPrincipal_W_RESIZE_CURSOR
#define MenuPrincipal_W_RESIZE_CURSOR 10L
#undef MenuPrincipal_E_RESIZE_CURSOR
#define MenuPrincipal_E_RESIZE_CURSOR 11L
#undef MenuPrincipal_HAND_CURSOR
#define MenuPrincipal_HAND_CURSOR 12L
#undef MenuPrincipal_MOVE_CURSOR
#define MenuPrincipal_MOVE_CURSOR 13L
#undef MenuPrincipal_NORMAL
#define MenuPrincipal_NORMAL 0L
#undef MenuPrincipal_ICONIFIED
#define MenuPrincipal_ICONIFIED 1L
#undef MenuPrincipal_MAXIMIZED_HORIZ
#define MenuPrincipal_MAXIMIZED_HORIZ 2L
#undef MenuPrincipal_MAXIMIZED_VERT
#define MenuPrincipal_MAXIMIZED_VERT 4L
#undef MenuPrincipal_MAXIMIZED_BOTH
#define MenuPrincipal_MAXIMIZED_BOTH 6L
#undef MenuPrincipal_serialVersionUID
#define MenuPrincipal_serialVersionUID 2673458971256075116i64
#undef MenuPrincipal_EXIT_ON_CLOSE
#define MenuPrincipal_EXIT_ON_CLOSE 3L
#ifdef __cplusplus
}
#endif
#endif
